# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    #- WP_VERSION=3.4.2 WP_MULTISITE=0
    #- WP_VERSION=3.3.3 WP_MULTISITE=0
    #- WP_VERSION=3.2.1 WP_MULTISITE=0 
    - WP_VERSION=master WP_MULTISITE=1
    #- WP_VERSION=3.4.2 WP_MULTISITE=1
    #- WP_VERSION=3.3.3 WP_MULTISITE=1 
    #- WP_VERSION=3.2.1 WP_MULTISITE=1

# Grab the setup script and execute
before_script:
    - wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script: phpunit

notifications:
    email:
        recipients:
          - ghost1227@reduxframework.com
          - dovy@reduxframework.com
        on_success: change
        on_failure: always

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup